source_name: "钢材缺陷检测摄像头"
source_type: "video"
source_mode: "rtsp_video"
source_list:
  - name: "v5lite_camera_0"
    url: ""
    dir: "v5lite/"
    metadata:
      resolution: "480p"
      fps: 30
      encoding: "mp4v"
      buffer_size: 2
    importance: 5
